export * from './template/button.reply';
export * from './template/confirm.reply';
export * from './template/carousel.reply';
export * from './template/image-carousel.reply';
export * from './template/image-map.reply';
export * from './template/flex.reply';
export * from './template/default-text.reply';
export * from './template/dodo.reply';
export * from './duanwu.reply';
